rvm:
- 1.9.3
- 2.1.5
- 2.2.2
- 2.3.4
- 2.4.1
sudo: false
dist: trusty
cache: bundler
install:
  - gem update --system 2.6.12  # https://github.com/rubygems/rubygems/issues/2024
  - gem update bundler
  - "bundle install --verbose --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}"
